### ISSUE TITLE
Gulp Ruby error on branches 2_05b, 2_05e, 2_06b (Windows)

### ISSUE THREAD

**Issue by fdmarcin** [planetoftheweb/sassEssentials#21]
When running `gulp` on these branches, I get this error:

```
internal/modules/cjs/loader.js:716
    throw err;
    ^

Error: Cannot find module 'jshint/src/cli'
Require stack:
- C:\Users\fdmarcin\Downloads\sassEssentials\node_modules\gulp-jshint\src\extract.js
- C:\Users\fdmarcin\Downloads\sassEssentials\node_modules\gulp-jshint\src\index.js
- C:\Users\fdmarcin\Downloads\sassEssentials\gulpfile.js
- C:\Users\fdmarcin\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\versioned\^4.0.0\index.js
- C:\Users\fdmarcin\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\index.js
- C:\Users\fdmarcin\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:713:15)
    at Function.Module._load (internal/modules/cjs/loader.js:618:27)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (C:\Users\fdmarcin\Downloads\sassEssentials\node_modules\gulp-jshint\src\extract.js:1:17)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\fdmarcin\\Downloads\\sassEssentials\\node_modules\\gulp-jshint\\src\\extract.js',
    'C:\\Users\\fdmarcin\\Downloads\\sassEssentials\\node_modules\\gulp-jshint\\src\\index.js',
    'C:\\Users\\fdmarcin\\Downloads\\sassEssentials\\gulpfile.js',
    'C:\\Users\\fdmarcin\\AppData\\Roaming\\npm\\node_modules\\gulp\\node_modules\\gulp-cli\\lib\\versioned\\^4.0.0\\index.js',
    'C:\\Users\\fdmarcin\\AppData\\Roaming\\npm\\node_modules\\gulp\\node_modules\\gulp-cli\\index.js',
    'C:\\Users\\fdmarcin\\AppData\\Roaming\\npm\\node_modules\\gulp\\bin\\gulp.js'
  ]
}
```

I thought something got messed up in my installation of Ruby, Node, or Sass, but it works correctly in other branches.

OS: Windows
Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]
Gulp CLI version: 2.2.0
Gulp Local version: 4.0.2
Sass: Ruby Sass 3.7.4

**Comment by planetoftheweb** [comment]
I'm no longer using Ruby for this repo. I switched to node-sass and updated the gulp process to include browser-sync to avoid any npm installation issues. I had to push the new gulpfile and package.json to every branch and it looks like I had missed those for some reason. Thanks for letting me know. It should work now.
